### ISSUE TITLE
ipython loading error

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#27]
#### Traceback
It probably only occurs with `environment_gpu.yml`:

```vim
(dmri_seg) [tb571@grx06 cnn-test]$ ipython
Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/application/current.py", line 6, in <module>
    from contextvars import ContextVar
ModuleNotFoundError: No module named 'contextvars'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/bin/ipython", line 5, in <module>
    from IPython import start_ipython
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 19, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 38, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 28, in <module>
    from .application.current import get_app
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/application/current.py", line 8, in <module>
    from prompt_toolkit.eventloop.dummy_contextvars import ContextVar  # type: ignore
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/eventloop/__init__.py", line 1, in <module>
    from .async_generator import generator_to_async_generator
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dmri_seg/lib/python3.6/site-packages/prompt_toolkit/eventloop/async_generator.py", line 5, in <module>
    from typing import AsyncGenerator, Callable, Iterable, TypeVar, Union
ImportError: cannot import name 'AsyncGenerator'
```

#### Solution
```
pip install contextvars
pip install --upgrade prompt-toolkit==2.0.1
```

**Comment by tashrifbillah** [comment]
No longer relevant.
